### ISSUE TITLE
Build failing for MacOS

### ISSUE THREAD

**Issue by Rob-Rychs** [protonmail-desktop/application#152]
Hello,

After downloading and running `yarn install` I am unable to run `yarn run dist` from the source.

The command fails with the following error outputted in terminal.

```BASH
yarn run v1.3.2
$ electron-builder
electron-builder 19.33.0
Rebuilding native production dependencies for darwin:x64
Rebuilding native dependency node-sass
Packaging for darwin x64 using electron 1.7.8 to dist/mac
Error: Application entry file "app/background.js" in the "/Users/rob/Desktop/application/dist/mac/Protonmail Desktop.app/Contents/Resources/app.asar" does not exist. Seems like a wrong configuration.
    at error (/Users/rob/Desktop/application/node_modules/electron-builder/src/util/asarUtil.ts:246:12)
    at /Users/rob/Desktop/application/node_modules/electron-builder/src/util/asarUtil.ts:272:11
    at Generator.next (<anonymous>)
    at /Users/rob/Desktop/application/node_modules/graceful-fs/polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:153:5)
From previous event:
    at checkFileInArchive (/Users/rob/Desktop/application/node_modules/electron-builder/out/util/asarUtil.js:52:22)
    at /Users/rob/Desktop/application/node_modules/electron-builder/src/platformPackager.ts:305:13
    at Generator.next (<anonymous>)
From previous event:
    at MacPackager.checkFileInPackage (/Users/rob/Desktop/application/node_modules/electron-builder/out/platformPackager.js:374:11)
    at /Users/rob/Desktop/application/node_modules/electron-builder/src/platformPackager.ts:353:16
    at Generator.next (<anonymous>)
    at /Users/rob/Desktop/application/node_modules/graceful-fs/polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:153:5)
From previous event:
    at MacPackager.sanityCheckPackage (/Users/rob/Desktop/application/node_modules/electron-builder/out/platformPackager.js:392:11)
    at /Users/rob/Desktop/application/node_modules/electron-builder/src/platformPackager.ts:198:16
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at MacPackager.doPack (/Users/rob/Desktop/application/node_modules/electron-builder/out/platformPackager.js:252:11)
    at /Users/rob/Desktop/application/node_modules/electron-builder/src/macPackager.ts:87:71
    at Generator.next (<anonymous>)
From previous event:
    at MacPackager.pack (/Users/rob/Desktop/application/node_modules/electron-builder/out/macPackager.js:183:11)
    at /Users/rob/Desktop/application/node_modules/electron-builder/src/packager.ts:260:24
From previous event:
    at Packager.doBuild (/Users/rob/Desktop/application/node_modules/electron-builder/out/packager.js:344:11)
    at /Users/rob/Desktop/application/node_modules/electron-builder/src/packager.ts:186:52
    at Generator.next (<anonymous>)
From previous event:
    at Packager.build (/Users/rob/Desktop/application/node_modules/electron-builder/out/packager.js:263:11)
    at /Users/rob/Desktop/application/node_modules/electron-builder/src/builder.ts:283:40
    at Generator.next (<anonymous>)
From previous event:
    at build (/Users/rob/Desktop/application/node_modules/electron-builder/out/builder.js:63:21)
    at loadEnv.then (/Users/rob/Desktop/application/node_modules/electron-builder/src/cli/cli.ts:49:4)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at Object.args [as handler] (/Users/rob/Desktop/application/node_modules/electron-builder/src/cli/cli.ts:49:4)
    at Object.runCommand (/Users/rob/Desktop/application/node_modules/yargs/lib/command.js:226:22)
    at Object.parseArgs [as _parseArgs] (/Users/rob/Desktop/application/node_modules/yargs/yargs.js:998:24)
    at Object.get [as argv] (/Users/rob/Desktop/application/node_modules/yargs/yargs.js:912:21)
    at Object.<anonymous> (/Users/rob/Desktop/application/node_modules/electron-builder/src/cli/cli.ts:43:15)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
error Command failed with exit code 255.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Can someone please issue some guidance on this error? Obviously I've looked and background.js does indeed exist in src/

Your help is much appreciated.

-Protonmail backer.

**Comment by kontrollanten** [comment]
Hi Rob! Is it the latest repo and without any changes?

If you just want to use the application you download the binary from our latest release

**Comment by Rob-Rychs** [comment]
Yes it's the latest repo without changes. 

Thanks I will look into installing from binary. 

Also wanted to take a look at #149, should be possible with crypto module but up to user if they want to save pw locally...

**Comment by kontrollanten** [comment]
Okay. I'm also running OS X High Sierra 10.13.1, but it works fine. Which node and npm versions are you running? I'll look deeper into this during the weekend

**Comment by Rob-Rychs** [comment]
```
node -v v8.9.1
npm -v 5.5.1
yarn -v 1.3.2
```

**Comment by kontrollanten** [comment]
Sorry for late response. Now I saw what's wrong. You have to build the app before packaging it. Run the following

    $ yarn build
    $ yarn dist

And it should work fine. I'll update the README to clarify this.
