### ISSUE TITLE
I got this "auto updater failed error" using 0.5.8 on ubuntu 16.04

### ISSUE THREAD

**Issue by sudoyang** [protonmail-desktop/application#171]
Ops! ProtonMail Desktops auto updater failed. Check https://github.com/protonmail-desktop/application for the latest updates and please create an issue.

Anyone can help? Thanks!

**Comment by kontrollanten** [comment]
Thanks for your report! Which kind of binary are you using?

**Comment by sudoyang** [comment]
@kontrollanten Thanks for the relpy! I install it via 64 bit deb package.

**Comment by kontrollanten** [comment]
Okay. Is it like this every time you start the application? Are there any details provided in the dialog? If you try to open up the application from terminal (`protonmail-desktop`) do you get any information from there?

**Comment by sudoyang** [comment]
Yes, I have it everyone when starting the app. I only have a pop-up window showing the error message.

I tried start with terminal and got this in terminal

➜  ~ protonmail-desktop
Checking for update
Error: Error: ENOENT: no such file or directory, open '/opt/Protonmail Desktop/resources/app-update.yml'
    at /opt/Protonmail Desktop/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:362:27
    at Generator.next (<anonymous>)
From previous event:
    at AppImageUpdater.loadUpdateConfig (/opt/Protonmail Desktop/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:380:11)
    at Lazy.AppUpdater.configOnDisk.Lazy [as creator] (/opt/Protonmail Desktop/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:125:43)
    at Lazy.get value [as value] (/opt/Protonmail Desktop/resources/app.asar/node_modules/lazy-val/src/main.ts:18:23)
    at /opt/Protonmail Desktop/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:273:33
    at Generator.next (<anonymous>)
From previous event:
    at AppImageUpdater.doCheckForUpdates (/opt/Protonmail Desktop/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:338:11)
    at /opt/Protonmail Desktop/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:256:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at AppImageUpdater._checkForUpdates (/opt/Protonmail Desktop/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:292:11)
    at AppImageUpdater.checkForUpdates (/opt/Protonmail Desktop/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:205:35)
    at App.app$1.on (/opt/Protonmail Desktop/resources/app.asar/app/src/auto-updater.js:10:17)
    at emitTwo (events.js:111:20)
    at App.emit (events.js:194:7)

**Comment by kontrollanten** [comment]
According to https://github.com/electron-userland/electron-builder/issues/1138#issuecomment-336209761 it seems that only `checkForUpdatesAndNotify` (instead of currently used `checkForUpdates`) checks whether the current target has support for auto update.

It should be pretty easy to switch to `checkForUpdatesAndNotify`, but I need to read further to completely understand the flow when using that method.

Thanks for reporting! Hopefully we can fix this soon.

**Comment by sudoyang** [comment]
Great, thanks!

**Comment by kontrollanten** [comment]
@sudoyang Sorry for the late response. We've now done a pre release where this should've been fixed. Can you try to download and see if it works? https://github.com/protonmail-desktop/application/releases/tag/v1.0.0-beta.1

**Comment by sudoyang** [comment]
@kontrollanten Thanks for the information! But it still seems that something went wrong... 
Btw, I have updated my system to Ubuntu 18.10.

Here are details:

➜  ~ protonmail-desktop 
(electron) 'app.makeSingleInstance(cb)' is deprecated. Use 'app.requestSingleInstanceLock() and app.on('second-instance', cb)' instead.
APPIMAGE env is not defined, current application is not an AppImage
Checking for update
Error: Error: ENOENT: no such file or directory, open '/opt/Protonmail Desktop/resources/app-update.yml'
    at readFile (/opt/Protonmail Desktop/resources/app.asar/app/webpack:/node_modules/electron-updater/out/AppUpdater.js:625:1)
    at Generator.next (<anonymous>)
From previous event:
    at t.AppImageUpdater.loadUpdateConfig (/opt/Protonmail Desktop/resources/app.asar/app/webpack:/node_modules/electron-updater/out/AppUpdater.js:620:1)
    at t.Lazy.loadUpdateConfig (/opt/Protonmail Desktop/resources/app.asar/app/webpack:/node_modules/electron-updater/out/AppUpdater.js:221:1)
    at t.Lazy.creator [as value] (/opt/Protonmail Desktop/resources/app.asar/app/webpack:/node_modules/lazy-val/out/main.js:17:1)
    at value (/opt/Protonmail Desktop/resources/app.asar/app/webpack:/node_modules/electron-updater/out/AppUpdater.js:503:1)
    at Generator.next (<anonymous>)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at t.AppImageUpdater.getUpdateInfoAndProvider (/opt/Protonmail Desktop/resources/app.asar/app/webpack:/node_modules/electron-updater/out/AppUpdater.js:499:1)
    at getUpdateInfoAndProvider (/opt/Protonmail Desktop/resources/app.asar/app/webpack:/node_modules/electron-updater/out/AppUpdater.js:532:1)
    at Generator.next (<anonymous>)
From previous event:
    at t.AppImageUpdater.doCheckForUpdates (/opt/Protonmail Desktop/resources/app.asar/app/webpack:/node_modules/electron-updater/out/AppUpdater.js:529:1)
    at t.AppImageUpdater.doCheckForUpdates [as checkForUpdates] (/opt/Protonmail Desktop/resources/app.asar/app/webpack:/node_modules/electron-updater/out/AppUpdater.js:361:1)
    at App.checkForUpdates (/opt/Protonmail Desktop/resources/app.asar/app/webpack:/src/main/auto-updater.js:31:1)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Unhandled rejection Error: ENOENT: no such file or directory, open '/opt/Protonmail Desktop/resources/app-update.yml'
    at readFile (/opt/Protonmail Desktop/resources/app.asar/app/webpack:/node_modules/electron-updater/out/AppUpdater.js:625:1)
    at Generator.next (<anonymous>)
From previous event:
    at t.AppImageUpdater.loadUpdateConfig (/opt/Protonmail Desktop/resources/app.asar/app/webpack:/node_modules/electron-updater/out/AppUpdater.js:620:1)
    at t.Lazy.loadUpdateConfig (/opt/Protonmail Desktop/resources/app.asar/app/webpack:/node_modules/electron-updater/out/AppUpdater.js:221:1)
    at t.Lazy.creator [as value] (/opt/Protonmail Desktop/resources/app.asar/app/webpack:/node_modules/lazy-val/out/main.js:17:1)
    at value (/opt/Protonmail Desktop/resources/app.asar/app/webpack:/node_modules/electron-updater/out/AppUpdater.js:503:1)
    at Generator.next (<anonymous>)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at t.AppImageUpdater.getUpdateInfoAndProvider (/opt/Protonmail Desktop/resources/app.asar/app/webpack:/node_modules/electron-updater/out/AppUpdater.js:499:1)
    at getUpdateInfoAndProvider (/opt/Protonmail Desktop/resources/app.asar/app/webpack:/node_modules/electron-updater/out/AppUpdater.js:532:1)
    at Generator.next (<anonymous>)
From previous event:
    at t.AppImageUpdater.doCheckForUpdates (/opt/Protonmail Desktop/resources/app.asar/app/webpack:/node_modules/electron-updater/out/AppUpdater.js:529:1)
    at t.AppImageUpdater.doCheckForUpdates [as checkForUpdates] (/opt/Protonmail Desktop/resources/app.asar/app/webpack:/node_modules/electron-updater/out/AppUpdater.js:361:1)
    at App.checkForUpdates (/opt/Protonmail Desktop/resources/app.asar/app/webpack:/src/main/auto-updater.js:31:1)
    at process._tickCallback (internal/process/next_tick.js:68:7)


![captured_20181127_14 11 51_001](https://user-images.githubusercontent.com/2531404/49105550-d46bb700-f24e-11e8-9bac-7e1c25c83e6e.png)

**Comment by kontrollanten** [comment]
Thanks for your quick response! I hoped it was possible to check for new versions even if auto update isn't supported, but it seems that it's not. I'll dig a bit more into this before I remove it.

**Comment by kontrollanten** [comment]
I get the feeling that electron-builder recommends to only build AppImage for Linux. I'm thinking about if we should just remove the other builds, but I'm not an experienced Linux user so I don't know if that's a bad thing. @sudoyang Is there any reason that you've choose deb instead of AppImage?

**Comment by sudoyang** [comment]
@kontrollanten In general, deb package follows the system setting better, for example, the system theme. In the case of protonmail-desktop, AppImage is equally good since it is mostly a webpage. So I do not mind to use AppImage instead.

**Comment by kontrollanten** [comment]
@BeatPlus do you have any opinions about this?

**Comment by sudoyang** [comment]
AppImage seems to have some problem too. Or is it due to my system setting?

➜  Downloads chmod a+x protonmail-desktop-1.0.0-beta.1-x86_64.AppImage 
➜  Downloads ./protonmail-desktop-1.0.0-beta.1-x86_64.AppImage 
(electron) 'app.makeSingleInstance(cb)' is deprecated. Use 'app.requestSingleInstanceLock() and app.on('second-instance', cb)' instead.
Checking for update
Error: HttpError: 404 Not Found
"method: undefined url: https://github.com/protonmail-desktop/application/releases/download/v1.0.0-beta.2/latest-linux.yml\n\nPlease double check that your authentication token is correct. Due to security reasons actual status maybe not reported, but 404.\n"
Headers: {
  "cache-control": [
    "no-cache"
  ],
  "content-encoding": [
    "gzip"
  ],
  "content-security-policy": [
    "default-src 'none'; base-uri 'self'; connect-src 'self'; form-action 'self'; img-src 'self' data:; script-src 'self'; style-src 'unsafe-inline'"
  ],
  "content-type": [
    "text/plain; charset=utf-8"
  ],
  "date": [
    "Thu, 29 Nov 2018 00:16:31 GMT"
  ],
  "expect-ct": [
    "max-age=2592000, report-uri=\"https://api.github.com/_private/browser/errors\""
  ],
  "server": [
    "GitHub.com"
  ],
  "set-cookie": [
    "has_recent_activity=1; path=/; expires=Thu, 29 Nov 2018 01:16:31 -0000",
    "logged_in=no; domain=.github.com; path=/; expires=Mon, 29 Nov 2038 00:16:31 -0000; secure; HttpOnly",
    "_gh_sess=NGpKRHM4ZFRBcUZXRi9tMDVVaTZNTDFCbVQzNzZHaTMzc3VQMFVnb0lYYmRwVFpwY2ZKYTRDN1dacVB6VHBXQ0N6bDdjdUxOQmdlL1VlZFRnR2tqTVF3WTRsbUowVmg4cTY5WWVCc2x1R0NWdkVscThsdzFCZUJqY2ZNMVAxcTZUUHh3aHMyaCtIVmw3TDV0eE5FNmNkenAybFQ0YXZCelplYjJJVk9HTmVzK1dQTU5HL3laazAwRytsd2VqNE51aDNxeGpXbTkvT1gvQVIyTC9tdklaQT09LS0xaFpEd0hncjJqSTVUNDdMR01lWjhBPT0%3D--e77f5617e1d95142135cac709874c48580b69062; path=/; secure; HttpOnly"
  ],
  "status": [
    "404 Not Found"
  ],
  "strict-transport-security": [
    "max-age=31536000; includeSubdomains; preload"
  ],
  "transfer-encoding": [
    "chunked"
  ],
  "vary": [
    "X-PJAX"
  ],
  "x-content-type-options": [
    "nosniff"
  ],
  "x-frame-options": [
    "deny"
  ],
  "x-github-request-id": [
    "AA4E:2DB7:2BC550:41E116:5BFF2FDF"
  ],
  "x-request-id": [
    "7c359d01-84bc-4c7b-833c-3d7175ab24bc"
  ],
  "x-xss-protection": [
    "1; mode=block"
  ]
}
    at d (/tmp/.mount_protonioN1Rx/resources/app.asar/app/webpack:/node_modules/builder-util-runtime/out/httpExecutor.js:102:1)
    at t.ElectronHttpExecutor.createHttpError [as handleResponse] (/tmp/.mount_protonioN1Rx/resources/app.asar/app/webpack:/node_modules/builder-util-runtime/out/httpExecutor.js:185:1)
    at ClientRequest.handleResponse (/tmp/.mount_protonioN1Rx/resources/app.asar/app/webpack:/node_modules/builder-util-runtime/out/httpExecutor.js:151:1)
    at ClientRequest.emit (events.js:182:13)
    at URLRequest.ClientRequest.urlRequest.on (/tmp/.mount_protonioN1Rx/resources/electron.asar/browser/api/net.js:207:12)
    at URLRequest.emit (events.js:182:13)
From previous event:
    at t.GitHubProvider.getLatestVersion (/tmp/.mount_protonioN1Rx/resources/app.asar/app/webpack:/node_modules/electron-updater/out/providers/GitHubProvider.js:105:1)
    at getLatestVersion (/tmp/.mount_protonioN1Rx/resources/app.asar/app/webpack:/node_modules/electron-updater/out/AppUpdater.js:512:1)
    at Generator.next (<anonymous>)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at t.AppImageUpdater.getUpdateInfoAndProvider (/tmp/.mount_protonioN1Rx/resources/app.asar/app/webpack:/node_modules/electron-updater/out/AppUpdater.js:499:1)
    at getUpdateInfoAndProvider (/tmp/.mount_protonioN1Rx/resources/app.asar/app/webpack:/node_modules/electron-updater/out/AppUpdater.js:532:1)
    at Generator.next (<anonymous>)
From previous event:
    at t.AppImageUpdater.doCheckForUpdates (/tmp/.mount_protonioN1Rx/resources/app.asar/app/webpack:/node_modules/electron-updater/out/AppUpdater.js:529:1)
    at t.AppImageUpdater.doCheckForUpdates [as checkForUpdates] (/tmp/.mount_protonioN1Rx/resources/app.asar/app/webpack:/node_modules/electron-updater/out/AppUpdater.js:361:1)
    at t.AppImageUpdater.checkForUpdates [as checkForUpdatesAndNotify] (/tmp/.mount_protonioN1Rx/resources/app.asar/app/webpack:/node_modules/electron-updater/out/AppUpdater.js:389:1)
    at App.checkForUpdatesAndNotify (/tmp/.mount_protonioN1Rx/resources/app.asar/app/webpack:/src/main/auto-updater.js:8:1)
    at App.emit (events.js:187:15)
(node:25451) UnhandledPromiseRejectionWarning: HttpError: 404 Not Found
"method: undefined url: https://github.com/protonmail-desktop/application/releases/download/v1.0.0-beta.2/latest-linux.yml\n\nPlease double check that your authentication token is correct. Due to security reasons actual status maybe not reported, but 404.\n"
Headers: {
  "cache-control": [
    "no-cache"
  ],
  "content-encoding": [
    "gzip"
  ],
  "content-security-policy": [
    "default-src 'none'; base-uri 'self'; connect-src 'self'; form-action 'self'; img-src 'self' data:; script-src 'self'; style-src 'unsafe-inline'"
  ],
  "content-type": [
    "text/plain; charset=utf-8"
  ],
  "date": [
    "Thu, 29 Nov 2018 00:16:31 GMT"
  ],
  "expect-ct": [
    "max-age=2592000, report-uri=\"https://api.github.com/_private/browser/errors\""
  ],
  "server": [
    "GitHub.com"
  ],
  "set-cookie": [
    "has_recent_activity=1; path=/; expires=Thu, 29 Nov 2018 01:16:31 -0000",
    "logged_in=no; domain=.github.com; path=/; expires=Mon, 29 Nov 2038 00:16:31 -0000; secure; HttpOnly",
    "_gh_sess=NGpKRHM4ZFRBcUZXRi9tMDVVaTZNTDFCbVQzNzZHaTMzc3VQMFVnb0lYYmRwVFpwY2ZKYTRDN1dacVB6VHBXQ0N6bDdjdUxOQmdlL1VlZFRnR2tqTVF3WTRsbUowVmg4cTY5WWVCc2x1R0NWdkVscThsdzFCZUJqY2ZNMVAxcTZUUHh3aHMyaCtIVmw3TDV0eE5FNmNkenAybFQ0YXZCelplYjJJVk9HTmVzK1dQTU5HL3laazAwRytsd2VqNE51aDNxeGpXbTkvT1gvQVIyTC9tdklaQT09LS0xaFpEd0hncjJqSTVUNDdMR01lWjhBPT0%3D--e77f5617e1d95142135cac709874c48580b69062; path=/; secure; HttpOnly"
  ],
  "status": [
    "404 Not Found"
  ],
  "strict-transport-security": [
    "max-age=31536000; includeSubdomains; preload"
  ],
  "transfer-encoding": [
    "chunked"
  ],
  "vary": [
    "X-PJAX"
  ],
  "x-content-type-options": [
    "nosniff"
  ],
  "x-frame-options": [
    "deny"
  ],
  "x-github-request-id": [
    "AA4E:2DB7:2BC550:41E116:5BFF2FDF"
  ],
  "x-request-id": [
    "7c359d01-84bc-4c7b-833c-3d7175ab24bc"
  ],
  "x-xss-protection": [
    "1; mode=block"
  ]
}
    at d (/tmp/.mount_protonioN1Rx/resources/app.asar/app/webpack:/node_modules/builder-util-runtime/out/httpExecutor.js:102:1)
    at t.ElectronHttpExecutor.createHttpError [as handleResponse] (/tmp/.mount_protonioN1Rx/resources/app.asar/app/webpack:/node_modules/builder-util-runtime/out/httpExecutor.js:185:1)
    at ClientRequest.handleResponse (/tmp/.mount_protonioN1Rx/resources/app.asar/app/webpack:/node_modules/builder-util-runtime/out/httpExecutor.js:151:1)
    at ClientRequest.emit (events.js:182:13)
    at URLRequest.ClientRequest.urlRequest.on (/tmp/.mount_protonioN1Rx/resources/electron.asar/browser/api/net.js:207:12)
    at URLRequest.emit (events.js:182:13)
From previous event:
    at t.GitHubProvider.getLatestVersion (/tmp/.mount_protonioN1Rx/resources/app.asar/app/webpack:/node_modules/electron-updater/out/providers/GitHubProvider.js:105:1)
    at getLatestVersion (/tmp/.mount_protonioN1Rx/resources/app.asar/app/webpack:/node_modules/electron-updater/out/AppUpdater.js:512:1)
    at Generator.next (<anonymous>)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at t.AppImageUpdater.getUpdateInfoAndProvider (/tmp/.mount_protonioN1Rx/resources/app.asar/app/webpack:/node_modules/electron-updater/out/AppUpdater.js:499:1)
    at getUpdateInfoAndProvider (/tmp/.mount_protonioN1Rx/resources/app.asar/app/webpack:/node_modules/electron-updater/out/AppUpdater.js:532:1)
    at Generator.next (<anonymous>)
From previous event:
    at t.AppImageUpdater.doCheckForUpdates (/tmp/.mount_protonioN1Rx/resources/app.asar/app/webpack:/node_modules/electron-updater/out/AppUpdater.js:529:1)
    at t.AppImageUpdater.doCheckForUpdates [as checkForUpdates] (/tmp/.mount_protonioN1Rx/resources/app.asar/app/webpack:/node_modules/electron-updater/out/AppUpdater.js:361:1)
    at t.AppImageUpdater.checkForUpdates [as checkForUpdatesAndNotify] (/tmp/.mount_protonioN1Rx/resources/app.asar/app/webpack:/node_modules/electron-updater/out/AppUpdater.js:389:1)
    at App.checkForUpdatesAndNotify (/tmp/.mount_protonioN1Rx/resources/app.asar/app/webpack:/src/main/auto-updater.js:8:1)
    at App.emit (events.js:187:15)
(node:25451) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:25451) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Unhandled rejection HttpError: 404 Not Found
"method: undefined url: https://github.com/protonmail-desktop/application/releases/download/v1.0.0-beta.2/latest-linux.yml\n\nPlease double check that your authentication token is correct. Due to security reasons actual status maybe not reported, but 404.\n"
Headers: {
  "cache-control": [
    "no-cache"
  ],
  "content-encoding": [
    "gzip"
  ],
  "content-security-policy": [
    "default-src 'none'; base-uri 'self'; connect-src 'self'; form-action 'self'; img-src 'self' data:; script-src 'self'; style-src 'unsafe-inline'"
  ],
  "content-type": [
    "text/plain; charset=utf-8"
  ],
  "date": [
    "Thu, 29 Nov 2018 00:16:31 GMT"
  ],
  "expect-ct": [
    "max-age=2592000, report-uri=\"https://api.github.com/_private/browser/errors\""
  ],
  "server": [
    "GitHub.com"
  ],
  "set-cookie": [
    "has_recent_activity=1; path=/; expires=Thu, 29 Nov 2018 01:16:31 -0000",
    "logged_in=no; domain=.github.com; path=/; expires=Mon, 29 Nov 2038 00:16:31 -0000; secure; HttpOnly",
    "_gh_sess=NGpKRHM4ZFRBcUZXRi9tMDVVaTZNTDFCbVQzNzZHaTMzc3VQMFVnb0lYYmRwVFpwY2ZKYTRDN1dacVB6VHBXQ0N6bDdjdUxOQmdlL1VlZFRnR2tqTVF3WTRsbUowVmg4cTY5WWVCc2x1R0NWdkVscThsdzFCZUJqY2ZNMVAxcTZUUHh3aHMyaCtIVmw3TDV0eE5FNmNkenAybFQ0YXZCelplYjJJVk9HTmVzK1dQTU5HL3laazAwRytsd2VqNE51aDNxeGpXbTkvT1gvQVIyTC9tdklaQT09LS0xaFpEd0hncjJqSTVUNDdMR01lWjhBPT0%3D--e77f5617e1d95142135cac709874c48580b69062; path=/; secure; HttpOnly"
  ],
  "status": [
    "404 Not Found"
  ],
  "strict-transport-security": [
    "max-age=31536000; includeSubdomains; preload"
  ],
  "transfer-encoding": [
    "chunked"
  ],
  "vary": [
    "X-PJAX"
  ],
  "x-content-type-options": [
    "nosniff"
  ],
  "x-frame-options": [
    "deny"
  ],
  "x-github-request-id": [
    "AA4E:2DB7:2BC550:41E116:5BFF2FDF"
  ],
  "x-request-id": [
    "7c359d01-84bc-4c7b-833c-3d7175ab24bc"
  ],
  "x-xss-protection": [
    "1; mode=block"
  ]
}
    at d (/tmp/.mount_protonioN1Rx/resources/app.asar/app/webpack:/node_modules/builder-util-runtime/out/httpExecutor.js:102:1)
    at t.ElectronHttpExecutor.createHttpError [as handleResponse] (/tmp/.mount_protonioN1Rx/resources/app.asar/app/webpack:/node_modules/builder-util-runtime/out/httpExecutor.js:185:1)
    at ClientRequest.handleResponse (/tmp/.mount_protonioN1Rx/resources/app.asar/app/webpack:/node_modules/builder-util-runtime/out/httpExecutor.js:151:1)
    at ClientRequest.emit (events.js:182:13)
    at URLRequest.ClientRequest.urlRequest.on (/tmp/.mount_protonioN1Rx/resources/electron.asar/browser/api/net.js:207:12)
    at URLRequest.emit (events.js:182:13)
From previous event:
    at t.GitHubProvider.getLatestVersion (/tmp/.mount_protonioN1Rx/resources/app.asar/app/webpack:/node_modules/electron-updater/out/providers/GitHubProvider.js:105:1)
    at getLatestVersion (/tmp/.mount_protonioN1Rx/resources/app.asar/app/webpack:/node_modules/electron-updater/out/AppUpdater.js:512:1)
    at Generator.next (<anonymous>)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at t.AppImageUpdater.getUpdateInfoAndProvider (/tmp/.mount_protonioN1Rx/resources/app.asar/app/webpack:/node_modules/electron-updater/out/AppUpdater.js:499:1)
    at getUpdateInfoAndProvider (/tmp/.mount_protonioN1Rx/resources/app.asar/app/webpack:/node_modules/electron-updater/out/AppUpdater.js:532:1)
    at Generator.next (<anonymous>)
From previous event:
    at t.AppImageUpdater.doCheckForUpdates (/tmp/.mount_protonioN1Rx/resources/app.asar/app/webpack:/node_modules/electron-updater/out/AppUpdater.js:529:1)
    at t.AppImageUpdater.doCheckForUpdates [as checkForUpdates] (/tmp/.mount_protonioN1Rx/resources/app.asar/app/webpack:/node_modules/electron-updater/out/AppUpdater.js:361:1)
    at t.AppImageUpdater.checkForUpdates [as checkForUpdatesAndNotify] (/tmp/.mount_protonioN1Rx/resources/app.asar/app/webpack:/node_modules/electron-updater/out/AppUpdater.js:389:1)
    at App.checkForUpdatesAndNotify (/tmp/.mount_protonioN1Rx/resources/app.asar/app/webpack:/src/main/auto-updater.js:8:1)
    at App.emit (events.js:187:15)

**Comment by kontrollanten** [comment]
@sudoyang The problem with AppImage was due to a failed release from our side. If you try again it should work now.

**Comment by kontrollanten** [comment]
Release **1.0.0-beta.3** should've solved the error message with the deb package.

**Comment by sudoyang** [comment]
It works both ways!
