### ISSUE TITLE
Old version published in AUR

### ISSUE THREAD

**Issue by zethexx** [protonmail-desktop/application#291]
I'm using Arch Linux x86_64, installed this package via this package from the [AUR](https://aur.archlinux.org/protonmail-desktop.git). Upon starting the application it gives an error and reports this to the command line:
```
App threw an error during load
TypeError: electron.app.makeSingleInstance is not a function
    at /usr/lib/protonmail-desktop/app/background.js:124:39
    at Object.<anonymous> (/usr/lib/protonmail-desktop/app/background.js:250:2)
    at Object.<anonymous> (/usr/lib/protonmail-desktop/app/background.js:252:3)
    at Module._compile (internal/modules/cjs/loader.js:693:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at loadApplicationPackage (/usr/lib/electron/resources/default_app.asar/main.js:119:12)
    at Object.<anonymous> (/usr/lib/electron/resources/default_app.asar/main.js:164:5)
A JavaScript error occurred in the main process
Uncaught Exception:
TypeError: electron.app.makeSingleInstance is not a function
    at /usr/lib/protonmail-desktop/app/background.js:124:39
    at Object.<anonymous> (/usr/lib/protonmail-desktop/app/background.js:250:2)
    at Object.<anonymous> (/usr/lib/protonmail-desktop/app/background.js:252:3)
    at Module._compile (internal/modules/cjs/loader.js:693:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at loadApplicationPackage (/usr/lib/electron/resources/default_app.asar/main.js:119:12)
    at Object.<anonymous> (/usr/lib/electron/resources/default_app.asar/main.js:164:5)
```
The application then hangs doing nothing, requiring killing the process.
Anyone know what is going on here and why it is giving an error?

**Comment by kontrollanten** [comment]
Thanks for reporting! That seems like a strange error. Can you try to install the latest version manually from https://github.com/protonmail-desktop/application/releases/tag/v1.0.0-beta.7 ?

**Comment by kontrollanten** [comment]
I've contacted the publisher in AUR to make it possible to update the version there. I actually didn't know it was published there.

**Comment by zethexx** [comment]
Hi yes and the version pulled from that link seems to work well. Had no related problems so far. Probably should have tried installing from Git directly before opening an issue. Sorry about that. Seems like the AUR version is inactive, probably best that I get builds from here
